import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import WineBg from './../public/wine-bg.jpg';
import Nav from './components/navbar/page';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative overflow-hidden`}
      >
        <Image
          src={WineBg}
          alt='Wine Background'
          fill
          className='absolute inset-0 z-0 h-full w-full object-cover'
          priority
        />
        <div className='relative z-10 flex flex-col'>
          <div className='z-50 w-full fixed top-0 p-6'>
            <Nav />
          </div>
          <div className='pt-24'>{children}</div>
        </div>
      </body>
    </html>
  );
}
